server:
  port: 8079
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: api-gateway
  config:
    import:
      - classpath:routes/services-routes.yaml